### PR TITLE
Cache storage

### PR DESCRIPTION
**Pull request by wbryceangell**
All Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Fork-Git-It/AnnotatedJS/pulls) for the same update/change?
- [x] Has the package version number been bumped?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by wbryceangell** [comment]
@kevinwonart feel free to ignore all of the changes to the `docs` folder. It is alot...

**Comment by wbryceangell** [comment]
This adds the `@CacheStorage` annotation and addresses the following:
- Create and export an interface that conforms to the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache)
- Create and export an interface that conforms to the [CacheStorage API](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage)
- Create and export an `@CacheStorage` class decorator that expects a class implementing the above interface
- Make sure that there is only a single instance of CacheStorage in the container, similar to `@Router` except it is optional

**Comment by wbryceangell** [comment]
@kevinwonart I removed the docs directory from git's tracking (so all of the files will be shown as being deleted) and I updated the documentation GitHub workflow. This way we won't have to review doc file changes every time

**Comment by kevinwonart** [comment]
looks good, I dont really feel like an authority as a reviewer, right now, but if this is just a bit of just workflow practice im jsut going to pass it for now(with minimal dilligence in this case) srry if this is bad practice lmk ><

**Comment by kevinwonart** [comment]
test

**Review by kevinwonart — APPROVED** [review]
got it

**Pull request merged**
